apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: debug
    app.kubernetes.io/part-of: debug
    app.kubernetes.io/managed-by: manual
spec:
  volumes:
    - name: tmp
      emptyDir: {}
    - name: zowe-runtime
      emptyDir: {}
    - name: zowe-config
      configMap:
        name: zowe-config
    - name: zowe-keystore
      projected:
        sources:
          - secret:
              name: zowe-certificates-secret
    - name: zowe-logs
      emptyDir: {}
    - name: zowe-workspace
      persistentVolumeClaim:
        claimName: zowe-workspace-pvc
  containers:
    - name: debug
      image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.1.0-ubuntu.v2-x-staging
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "10m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        privileged: false
        runAsNonRoot: true
        capabilities:
          drop:
            - all
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: zowe-runtime
          mountPath: "/home/zowe/runtime"
        - name: zowe-config
          mountPath: "/home/zowe/instance/zowe.yaml"
          subPath: zowe.yaml
          readOnly: true
        - name: zowe-keystore
          mountPath: "/home/zowe/keystore"
          readOnly: true
        - name: zowe-logs
          mountPath: "/home/zowe/instance/logs"
        - name: zowe-workspace
          mountPath: "/home/zowe/instance/workspace"
      command: ["/bin/bash", "-c"]
      args:
        - sleep 3600
      initContainers:
        - name: update-workspace-permission
          image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.1.0-ubuntu.v2-x-staging
          command: ['sh', '-c', 'OWNER=`stat -c "%u:%g" /home/zowe/instance/workspace` && PERMISSION=`stat -c "%a" /home/zowe/instance/workspace` && echo "Zowe workspace owner is ${OWNER} with ${PERMISSION} permission" && if [ "${OWNER}" != "20000:20000" -a "${PERMISSION}" != "777" ]; then chown -R 20000:20000 /home/zowe/instance/workspace; fi']
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: zowe-workspace
              mountPath: "/home/zowe/instance/workspace"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - all
              add:
                - CHOWN
            runAsUser: 0
            runAsGroup: 0
