---

# ============================================================================
# Clean up history job output
- import_role:
    name: configure
    tasks_from: purge_job_outputs
  when: cleanup_zowe_job_history

# ============================================================================
- import_role:
    name: configure
    tasks_from: locate_xmem

- import_role:
    name: configure
    tasks_from: locate_zowe_start

# ============================================================================
- name: Start Cross Memory Server
  import_role:
    name: zos
    tasks_from: opercmd
  vars:
    opercmd: "S {{ zowe_xmem_stc_name }}"

- name: Patch keyring for apiml
  raw: >-
    cat "{{ zowe_root_dir }}/components/api-mediation/bin/start.sh" | \
    sed -e "s+\\\${KEYSTORE_PASSWORD}+password+" | \
    sed -e "s+\\\${KEYSTORE_TYPE}+JCERACFKS+" | \
    sed -e "s+\\\${KEYSTORE}+safkeyring:////ZWESVUSR/ZoweKeyring+" | \
    sed -e "s+\\\${TRUSTSTORE}+safkeyring:////ZWESVUSR/ZoweKeyring+" | \
    sed -e "s+\\\${KEY_ALIAS}+ZOWE+" \
    > "{{ work_dir_remote }}/components/api-mediation/bin/start.sh"

- name: Show apiml run script
  raw: cat "{{ work_dir_remote }}/components/api-mediation/bin/start.sh"

- name: Start Zowe
  raw: "{{ zowe_start_path }}"

# ============================================================================
# Wait for services started
- import_role:
    name: start
    tasks_from: wait_for_zowe
